import { CSSProperties } from "react";

export const styles: { [key: string]: CSSProperties } = {
  main: {
    minHeight: "calc(100vh - 80px)",
    padding: "3rem 2rem",
    maxWidth: "1200px",
    margin: "0 auto",
  },
  hero: {
    textAlign: "center",
    marginBottom: "4rem",
    paddingTop: "2rem",
  },
  title: {
    fontSize: "3.5rem",
    fontWeight: 700,
    marginBottom: "1.5rem",
    color: "#1a1a1a",
    fontFamily: "var(--font-playfair)",
    lineHeight: 1.2,
  },
  titleAccent: {
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    backgroundClip: "text",
  },
  subtitle: {
    fontSize: "1.25rem",
    color: "#666",
    marginBottom: "2.5rem",
    maxWidth: "700px",
    margin: "0 auto 2.5rem",
    lineHeight: 1.6,
    fontFamily: "var(--font-lora)",
  },
  ctaContainer: {
    display: "flex",
    gap: "1rem",
    justifyContent: "center",
    flexWrap: "wrap",
  },
  primaryButton: {
    padding: "1rem 2.5rem",
    fontSize: "1.1rem",
    fontWeight: 600,
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    color: "#fff",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    textDecoration: "none",
    transition: "transform 0.2s, box-shadow 0.2s",
    boxShadow: "0 4px 15px rgba(102, 126, 234, 0.4)",
    display: "inline-block",
  },
  secondaryButton: {
    padding: "1rem 2.5rem",
    fontSize: "1.1rem",
    fontWeight: 600,
    background: "#fff",
    color: "#667eea",
    border: "2px solid #667eea",
    borderRadius: "8px",
    cursor: "pointer",
    textDecoration: "none",
    transition: "all 0.2s",
    display: "inline-block",
  },
  features: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
    gap: "2rem",
    marginBottom: "4rem",
  },
  featureCard: {
    padding: "2rem",
    background: "#fff",
    borderRadius: "12px",
    boxShadow: "0 4px 20px rgba(0, 0, 0, 0.08)",
    textAlign: "center",
    transition: "transform 0.2s, box-shadow 0.2s",
  },
  featureIcon: {
    fontSize: "3rem",
    marginBottom: "1rem",
  },
  featureTitle: {
    fontSize: "1.5rem",
    fontWeight: 700,
    marginBottom: "0.75rem",
    color: "#1a1a1a",
    fontFamily: "var(--font-playfair)",
  },
  featureDescription: {
    color: "#666",
    lineHeight: 1.6,
    fontFamily: "var(--font-lora)",
  },
  infoSection: {
    textAlign: "center",
    padding: "3rem 2rem",
    background: "linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)",
    borderRadius: "16px",
    marginTop: "3rem",
  },
  infoTitle: {
    fontSize: "2.5rem",
    fontWeight: 700,
    marginBottom: "2.5rem",
    color: "#1a1a1a",
    fontFamily: "var(--font-playfair)",
  },
  steps: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: "1.5rem",
    flexWrap: "wrap",
  },
  step: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "1rem",
  },
  stepNumber: {
    width: "60px",
    height: "60px",
    borderRadius: "50%",
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "1.5rem",
    fontWeight: 700,
  },
  stepText: {
    fontSize: "1rem",
    color: "#333",
    fontWeight: 500,
    maxWidth: "150px",
  },
  stepArrow: {
    fontSize: "2rem",
    color: "#667eea",
    fontWeight: 700,
  },
};
