export const popupStyles = {
  overlay: {
    position: "fixed" as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
    animation: "fadeIn 0.3s ease-in-out",
  },
  popup: {
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    padding: "2.5rem",
    borderRadius: "16px",
    boxShadow: "0 20px 60px rgba(0, 0, 0, 0.3)",
    textAlign: "center" as const,
    maxWidth: "500px",
    animation: "slideIn 0.3s ease-out",
  },
  icon: {
    fontSize: "4rem",
    color: "#fff",
    marginBottom: "1rem",
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    width: "80px",
    height: "80px",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    margin: "0 auto 1rem",
  },
  title: {
    fontSize: "2rem",
    fontWeight: 700,
    color: "#fff",
    marginBottom: "0.5rem",
    fontFamily: "var(--font-playfair)",
  },
  message: {
    fontSize: "1.1rem",
    color: "#fff",
    marginBottom: "1rem",
    opacity: 0.9,
  },
  url: {
    fontSize: "0.9rem",
    color: "#fff",
    backgroundColor: "rgba(0, 0, 0, 0.2)",
    padding: "0.75rem",
    borderRadius: "8px",
    wordBreak: "break-all" as const,
    fontFamily: "monospace",
  },
};
