import { CSSProperties } from "react";

export const styles: { [key: string]: CSSProperties } = {
  main: {
    minHeight: "calc(100vh - 80px)",
    padding: "2rem",
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
  },
  container: {
    maxWidth: "1200px",
    margin: "0 auto",
  },
  header: {
    textAlign: "center",
    marginBottom: "2.5rem",
    color: "#fff",
  },
  title: {
    fontSize: "3rem",
    fontWeight: 700,
    marginBottom: "0.5rem",
    fontFamily: "var(--font-playfair)",
    textShadow: "0 2px 10px rgba(0, 0, 0, 0.2)",
  },
  subtitle: {
    fontSize: "1.2rem",
    opacity: 0.95,
    fontFamily: "var(--font-lora)",
  },
  controlPanel: {
    background: "#fff",
    borderRadius: "16px",
    padding: "2rem",
    boxShadow: "0 8px 32px rgba(0, 0, 0, 0.1)",
    marginBottom: "2rem",
  },
  inputGroup: {
    marginBottom: "1.5rem",
  },
  label: {
    display: "block",
    fontSize: "0.95rem",
    fontWeight: 600,
    color: "#333",
    marginBottom: "0.5rem",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  input: {
    width: "100%",
    padding: "1rem",
    fontSize: "1rem",
    border: "2px solid #e0e0e0",
    borderRadius: "10px",
    outline: "none",
    transition: "all 0.3s",
    fontFamily: "monospace",
    boxSizing: "border-box",
  },
  hint: {
    fontSize: "0.85rem",
    color: "#666",
    marginTop: "0.5rem",
    fontStyle: "italic",
  },
  button: {
    width: "100%",
    padding: "1.1rem 2rem",
    fontSize: "1.1rem",
    fontWeight: 600,
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    color: "#fff",
    border: "none",
    borderRadius: "10px",
    cursor: "pointer",
    transition: "all 0.3s",
    boxShadow: "0 4px 15px rgba(102, 126, 234, 0.4)",
  },
  buttonDisabled: {
    background: "#9ca3af",
    cursor: "not-allowed",
    boxShadow: "none",
  },
  buttonContent: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.5rem",
  },
  spinner: {
    display: "inline-block",
    animation: "spin 1s linear infinite",
  },
  errorContainer: {
    background: "linear-gradient(135deg, #ff6b6b 0%, #ee5a6f 100%)",
    color: "#fff",
    padding: "1.25rem",
    borderRadius: "12px",
    marginBottom: "2rem",
    display: "flex",
    alignItems: "center",
    gap: "0.75rem",
    fontWeight: 500,
    boxShadow: "0 4px 15px rgba(255, 107, 107, 0.3)",
  },
  errorIcon: {
    fontSize: "1.5rem",
  },
  imageSection: {
    marginTop: "2rem",
  },
  imageCard: {
    background: "#fff",
    borderRadius: "16px",
    overflow: "hidden",
    boxShadow: "0 8px 32px rgba(0, 0, 0, 0.15)",
  },
  imageHeader: {
    padding: "1.5rem 2rem",
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    color: "#fff",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  imageTitle: {
    fontSize: "1.5rem",
    fontWeight: 700,
    margin: 0,
    fontFamily: "var(--font-playfair)",
  },
  badge: {
    background: "rgba(255, 255, 255, 0.25)",
    padding: "0.4rem 1rem",
    borderRadius: "20px",
    fontSize: "0.9rem",
    fontWeight: 600,
  },
  imageWrapper: {
    position: "relative",
    width: "100%",
    background: "#f8f9fa",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    minHeight: "400px",
  },
  image: {
    width: "100%",
    height: "auto",
    display: "block",
    objectFit: "contain",
    maxHeight: "700px",
  },
  metadataPanel: {
    padding: "1.5rem 2rem",
    background: "#f8f9fa",
    borderTop: "1px solid #e0e0e0",
  },
  metadataRow: {
    display: "flex",
    alignItems: "flex-start",
    gap: "1rem",
    marginBottom: "1rem",
  },
  metadataLabel: {
    fontSize: "0.9rem",
    fontWeight: 600,
    color: "#667eea",
    minWidth: "80px",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  metadataValue: {
    flex: 1,
    fontSize: "0.9rem",
    color: "#333",
    background: "#fff",
    padding: "0.5rem 0.75rem",
    borderRadius: "6px",
    border: "1px solid #e0e0e0",
    wordBreak: "break-all",
    fontFamily: "monospace",
  },
  actions: {
    padding: "1.5rem 2rem",
    display: "flex",
    gap: "1rem",
    flexWrap: "wrap",
    borderTop: "1px solid #e0e0e0",
  },
  actionButton: {
    flex: 1,
    minWidth: "200px",
    padding: "0.9rem 1.5rem",
    fontSize: "1rem",
    fontWeight: 600,
    background: "#fff",
    color: "#667eea",
    border: "2px solid #667eea",
    borderRadius: "8px",
    cursor: "pointer",
    transition: "all 0.2s",
    textDecoration: "none",
    display: "inline-block",
    textAlign: "center",
  },
  placeholder: {
    textAlign: "center",
    padding: "5rem 2rem",
    background: "rgba(255, 255, 255, 0.95)",
    borderRadius: "16px",
    marginTop: "2rem",
    boxShadow: "0 8px 32px rgba(0, 0, 0, 0.1)",
  },
  placeholderIcon: {
    fontSize: "5rem",
    marginBottom: "1.5rem",
    opacity: 0.6,
  },
  placeholderTitle: {
    fontSize: "1.8rem",
    fontWeight: 700,
    color: "#333",
    marginBottom: "0.75rem",
    fontFamily: "var(--font-playfair)",
  },
  placeholderText: {
    fontSize: "1.1rem",
    color: "#666",
    maxWidth: "500px",
    margin: "0 auto",
    fontFamily: "var(--font-lora)",
    lineHeight: 1.6,
  },
};
